package easy.string;

/**
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 * Example 1:
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * Example 2:
 * Input: s = "", t = "y"
 * Output: "y"
 */
public class FindTheDifference389 {
    public static char findTheDifference(String s, String t) {
        int sum = 0;
        for (char ss : t.toCharArray()) {
            sum += ss;
        }
        for (char ss : s.toCharArray()) {
            sum -= ss;
        }
        return (char) sum;
    }
}
